[package]
name = "tezos_interop_callback"
version = "1.2.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
ocaml-interop = { version = "0.7.0", features = ["without-ocamlopt"] }
# local dependencies
tezos_context = { path = "../context" }
