name: clippy

on:
  push:
    branches: [ master, develop ]
  pull_request:

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: OCaml/Opam cache
        id: tezedge-opam-cache
        uses: actions/cache@v2
        with:
          path: "~/.opam"
          key: tezedge-${{ matrix.os }}-ocaml-4.09.1
      - name: Setup OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.09.1
      - name: Set Opam env
        run: opam env >> $GITHUB_ENV
      - name: Add Opam switch to PATH
        run: opam var bin >> $GITHUB_PATH
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-12-31
          components: clippy
          override: true

      - name: lint
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all-targets -- -A clippy::too_many_arguments -A clippy::doc_markdown
